In [123]:
import numpy as np
import random
import math

In [124]:

label=[]
train=[]


data=np.random.randint(100, size=(100,3))
print(data)
print(type(data))

label.append(np.random.randint(100)%3)
test=data
#print(a)
#print(b)
#print(len(data))

[[ 8 96 24]
 [18 17 60]
 [46 38 42]
 [35 98 17]
 [63 47 79]
 [92 41 76]
 [50 68 64]
 [88 24 27]
 [ 3 94 48]
 [64 80 88]
 [55 53 36]
 [37 82 76]
 [82 99 54]
 [49 78 70]
 [29  4 44]
 [11 14 94]
 [75 98  6]
 [40 39 28]
 [ 0 89 38]
 [43 17 56]
 [51 21 45]
 [20  5 64]
 [82 27 87]
 [18 57 15]
 [15 49 78]
 [ 3 36 64]
 [ 8 16 89]
 [ 2  3 39]
 [49 42  6]
 [78 41 16]
 [48 71 81]
 [69 95 75]
 [11 39 26]
 [45 14 17]
 [91 45 93]
 [64 61 24]
 [16 95 47]
 [37 43 22]
 [19 69 70]
 [96 64 29]
 [38 24 13]
 [31 90  3]
 [ 0 64 46]
 [73 14  7]
 [58  3 59]
 [71 85 80]
 [93  1 53]
 [ 9 80  7]
 [ 5 58 70]
 [37 90 64]
 [73 81 97]
 [74  5 95]
 [ 5  4 51]
 [49 86  0]
 [37 65 39]
 [29 91 65]
 [22 53 29]
 [53 52 54]
 [35 31  3]
 [ 1 13 17]
 [62 24 10]
 [43 36 18]
 [59 68 65]
 [10 33  5]
 [51 54 94]
 [42 93 42]
 [75 44 18]
 [77 36 20]
 [72 80 31]
 [ 3 27 32]
 [49 42 66]
 [92 41 80]
 [50  5 90]
 [15 32 75]
 [50 11 14]
 [62 25 78]
 [65  9 72]
 [ 0 16 58]
 [52 67 51]
 [14 98  9]
 [43 17 10]
 [99 81 29]
 [34 91 71]
 [35

In [149]:


x=np.random.randint(100,size=100)
random.shuffle(x)
n=len(x)
te=[]

for i in range(n):
    if len(train) < 70:
        train.append(data[x[i]])
        x=np.delete(x,i)
        
    else:
        te.append(data[x[i]])

print(len(train))
print("Training set:\n")        
print(train)

print(len(te))
print("Test set: \n")
print(te)

print(len(x))

z = np.array([1,2,3,4])
y=[0,3]
z=np.delete(z,y)
z


70
Training set:

[array([ 8, 96, 24]), array([18, 17, 60]), array([46, 38, 42]), array([35, 98, 17]), array([63, 47, 79]), array([92, 41, 76]), array([50, 68, 64]), array([88, 24, 27]), array([ 3, 94, 48]), array([64, 80, 88]), array([55, 53, 36]), array([37, 82, 76]), array([82, 99, 54]), array([49, 78, 70]), array([29,  4, 44]), array([11, 14, 94]), array([75, 98,  6]), array([40, 39, 28]), array([ 0, 89, 38]), array([43, 17, 56]), array([51, 21, 45]), array([20,  5, 64]), array([82, 27, 87]), array([18, 57, 15]), array([15, 49, 78]), array([ 3, 36, 64]), array([ 8, 16, 89]), array([ 2,  3, 39]), array([49, 42,  6]), array([78, 41, 16]), array([48, 71, 81]), array([69, 95, 75]), array([11, 39, 26]), array([45, 14, 17]), array([91, 45, 93]), array([64, 61, 24]), array([16, 95, 47]), array([37, 43, 22]), array([19, 69, 70]), array([96, 64, 29]), array([38, 24, 13]), array([31, 90,  3]), array([ 0, 64, 46]), array([73, 14,  7]), array([58,  3, 59]), array([71, 85, 80]), array([93,  1, 